# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenerateSecurePillar < Formula
  desc "Create and update encrypted content or decrypt encrypted content in YAML files"
  homepage "https://github.com/Everbridge/generate-secure-pillar"
  version "1.0.597"

  on_macos do
    url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.597/generate-secure-pillar_1.0.597_Darwin_all.tar.gz"
    sha256 "52cd7d0a1138740a644a14fab263b004d99db2cf65f9f459685562ab18283ce8"

    def install
      bin.install "generate-secure-pillar"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.597/generate-secure-pillar_1.0.597_Linux_x86_64.tar.gz"
      sha256 "cd70ce7e778cdd3b17aa63a0ad6affb8523dbb878221f34c0d9123c11172f8fc"

      def install
        bin.install "generate-secure-pillar"
      end
    end
  end

  depends_on "gpg1"
end
