# This file was generated by GoReleaser. DO NOT EDIT.
class GenerateSecurePillar < Formula
  desc "Create and update encrypted content or decrypt encrypted content in YAML files"
  homepage "https://github.com/Everbridge/generate-secure-pillar"
  version "1.0.522"

  if OS.mac?
    url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.522/generate-secure-pillar_1.0.522_Darwin_x86_64.tar.gz"
    sha256 "859a682387ed8d7dc1ab9fff8f7738060dec4e109147242e0725bb9a296052c1"
  elsif OS.linux?
    url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.522/generate-secure-pillar_1.0.522_Linux_x86_64.tar.gz"
    sha256 "d9463f4f228343f020dec98ffe0d77756619b10cd4a80e43f2a75d833e87fc18"
  end
  
  depends_on "gpg1"

  def install
    bin.install "generate-secure-pillar"
  end
end
